### ISSUE TITLE
Calling `iq+` not from the current directory fails

### ISSUE THREAD

**Issue by schragge** [math-for-shell/iq4sh#2]
[`. ./iq`](https://github.com/math-for-shell/iq4sh/blob/84b3aa32816db9f1bfc187979710349e23d9fa1d/iq%2B#L465) will fail if `iq` and `iq+` are not in the current directory. Better would be
```
case $0 in *iq+)
    path="${0%/*}"
    [ "$0" == "$path" ] && path= || path="$path/"
    source=1 . ${path}iq
...
```

**Comment by math-for-shell** [comment]
This has been addressed -mostly by changing the instructions. Also, please not that the suggested fix includes a bashism, so is not usable. For easiest use of iq/iq+ put them in your PATH, or temporarily add the directory where they are located to your PATH.

**Comment by schragge** [comment]
> This has been addressed -mostly by changing the instructions.

I confirm that the latest snapshot fixes this. Thank you.

> Also, please not that the suggested fix includes a bashism, so is not usable.

Do you mean `==` instead of `=`? Sorry, this has somehow slipped through.

> For easiest use of iq/iq+ put them in your PATH

This is how I discovered the bug in the first place. I'm building an RPM package of it with [this spec file](https://app.box.com/s/xdcnioyzyuy54inhhhtuspfhmzu8qnx8).
